name: CI

on:
  push:
    branches:
      - main
      - case-key-paths
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-12:
    name: MacOS 12
    runs-on: macos-12
    strategy:
      matrix:
        xcode:
          - '14.2'
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Print Swift version
        run: swift --version
      - name: Run tests
        run: make test-swift

  linux:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-linux

  windows:
    name: Windows
    strategy:
      matrix:
        os: [windows-latest]
        config: ['debug', 'release']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.8.1-release
          tag: 5.8.1-RELEASE
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -c ${{ matrix.config }}
      - name: Run tests (debug only)
        # There is an issue that exists in the 5.8.1 toolchain
        # which fails on release configuration testing, but
        # this issue is fixed 5.9 so we can remove the if once
        # that is generally available.
        if: ${{ matrix.config == 'debug' }}
        run: swift test
